os: linux
dist: xenial
language: node_js
node_js:
  - '12'
  - '14'
  - '16'
branches:
  only:
    - main
cache:
  directories:
    - node_modules
install:
  - npm install
script:
  - npm test
  - npm run coveralls
