sudo: false
language: node_js
node_js:
  - '12'
  - '14'
branches:
  only:
    - main
cache:
  directories:
    - node_modules
install:
  - npm install
scripts:
  - npm install codecov -g
  - npm test
