name: Node.js CI

on:
  push:
    branches: ['rewrite']
  pull_request:
    branches: ['rewrite']

jobs:
  test:
    name: Node.js ${{ matrix.node-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version:
          - 14.x
          - 16.x
        os:
          - ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm test
